### ISSUE TITLE
JAR refuses to start

### ISSUE THREAD

**Issue by redhelling21** [karakasis/Path-of-Leveling#71]
Hello,
when I run the Jar, a small window "Running to Hillock" appears... then another one says "Error during Path of Leveling start up: null".
The logs provide :

```
2021-01-13 20:53:49.69


janv. 13, 2021 8:53:49 PM poe.level.data.Util httpToString
INFOS: Retrieving URL: https://api.github.com/rate_limit
janv. 13, 2021 8:53:51 PM poe.level.data.Util httpToString
INFOS: Retrieving URL: https://api.github.com/repos/karakasis/Path-of-Leveling/releases
janv. 13, 2021 8:53:51 PM poe.level.data.GithubHelper getLatestReleaseInfo
AVERTISSEMENT: Failed to find the PathOfLeveling.jar asset!
-POELevelFx- Setting keybind for : F4 for zones-hotkey-show_hide
-POELevelFx- Setting keybind for : F5 for level-hotkey-remind
-POELevelFx- Setting keybind for : Page Down for recipe-hotkey-mark
-POELevelFx- Setting keybind for : Page Up for recipe-hotkey-preview
-POELevelFx- Setting keybind for : Right for level-hotkey-beta-next
-POELevelFx- Setting keybind for : Left for level-hotkey-beta-previous
-POELevelFx- Setting keybind for : F12 for lock-keybinds
updateGemsPos x:-200.0 y: -200.0
updateLevelPos x:-200.0 y: -200.0
updateZonesPos x:-200.0 y: -200.0
janv. 13, 2021 8:53:52 PM poe.level.data.GithubHelper <init>
INFOS: Initializing new GithubHelper for karakasis on the master branch.
janv. 13, 2021 8:53:52 PM poe.level.data.Util httpToString
INFOS: Retrieving URL: https://api.github.com/repos/karakasis/Path-of-Leveling/branches
janv. 13, 2021 8:53:52 PM poe.level.data.GithubHelper getBranchSha
INFOS: Found branch SHA: 320adfc5ebb497ca664c038b668e99fb7e33befd
janv. 13, 2021 8:53:52 PM poe.level.data.Util httpToString
INFOS: Retrieving URL: https://api.github.com/repos/karakasis/Path-of-Leveling/commits?path=/json/gems.json&sha=320adfc5ebb497ca664c038b668e99fb7e33befd
janv. 13, 2021 8:53:52 PM poe.level.data.GithubHelper downloadGemsJsonFileIfNeeded
INFOS: Detected that the D:\Documents\Path of Leveling\json\gems.json needs to be downloaded.
janv. 13, 2021 8:53:53 PM poe.level.data.Util httpToString
INFOS: Retrieving URL: https://api.github.com/repos/karakasis/Path-of-Leveling/commits?path=/json/data.json&sha=320adfc5ebb497ca664c038b668e99fb7e33befd
janv. 13, 2021 8:53:53 PM poe.level.data.GithubHelper downloadDataJsonFileIfNeeded
INFOS: Detected that the D:\Documents\Path of Leveling\json\data.json needs to be downloaded.
Zone data loaded.
janv. 13, 2021 8:53:53 PM poe.level.fx.POELevelFx loadGemsFromMemory
INFOS: Gem Added Chaos Damage.png doesn't exist in D:\Documents\Path of Leveling\gems\icons\ downloading
java.io.FileNotFoundException: D:\Documents\Path of Leveling\gems\icons\Added Chaos Damage.png (Accès refusé)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at javax.imageio.stream.FileImageOutputStream.<init>(Unknown Source)
	at com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(Unknown Source)
	at javax.imageio.ImageIO.createImageOutputStream(Unknown Source)
	at javax.imageio.ImageIO.write(Unknown Source)
	at poe.level.fx.POELevelFx.downloadGemIcon(POELevelFx.java:966)
	at poe.level.fx.POELevelFx.loadGemsFromMemory(POELevelFx.java:918)
	at poe.level.fx.POELevelFx.init(POELevelFx.java:488)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Unknown Source)
janv. 13, 2021 8:53:54 PM poe.level.fx.POELevelFx init
GRAVE: Error during Path of Leveling start up: null
java.lang.NullPointerException
	at javax.imageio.ImageIO.write(Unknown Source)
	at poe.level.fx.POELevelFx.downloadGemIcon(POELevelFx.java:966)
	at poe.level.fx.POELevelFx.loadGemsFromMemory(POELevelFx.java:918)
	at poe.level.fx.POELevelFx.init(POELevelFx.java:488)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Unknown Source)

```

I tried running the JAR as admin, modifying the permissions on the Path of Leveling folder, but nothing.
I also tried to place the "gems" and "json" folders (and their content) before starting the JAR, but it just deletes them when started.

Is it because my Documents folder is on the D: drive ? How can I change the installation folder ?

Any ideas ?

**Comment by redhelling21** [comment]
Solved, for some reason my system seems to have troubles downloading the icon files, and placing them in the icons folder.
So I took the "gems" folder from the master, and directly copied it in Documents/Path of Leveling. Then I created a gems/icons folder, and copied all the gem icons inside it.
Then cleaned the rest of the Path of Leveling folder.
Thanks a lot to @karakasis for the help

**Comment by karakasis** [comment]
I'm glad we figured it out, It seems to be problem related to permission while writting a new File.
You tagged the wrong person there by the way

**Comment by redhelling21** [comment]
Sorry about that.
As a side note, the fact that the program get denied each time it tries to create a file prevent me from saving a build.

**Comment by karakasis** [comment]
Yeah, I forgot about that, makes sense.
I might have missed something in the code, can't really say for sure, and I'm no longer maintaining the code.
I can only suggest since this is permission related, to try and see If you can somehow allow write in the document folder.

**Comment by karakasis** [comment]
Otherwise you could fork the project, and replace the automated mkdir() in your documents folder with some hardcoded path to 
another disk drive, perhaps C will allow read/write and compile into another jar  that you use for personal use
